# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08my.proto\"1\n\x04\x46\x61\x63t\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x66\x61\x63t\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x05\" \n\x08\x46\x61\x63tList\x12\x14\n\x05\x66\x61\x63ts\x18\x01 \x03(\x0b\x32\x05.Fact\"\x16\n\x05\x45rror\x12\r\n\x05\x65rror\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'my_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FACT._serialized_start=12
  _FACT._serialized_end=61
  _FACTLIST._serialized_start=63
  _FACTLIST._serialized_end=95
  _ERROR._serialized_start=97
  _ERROR._serialized_end=119
# @@protoc_insertion_point(module_scope)
